name: EpicVouchers
main: com.songoda.epicvouchers.EpicVouchers
version: maven-version-number
author: Songoda
website: https://songoda.host/epicvouchers
description: Enhance your server with awesome customizable vouchers with a lot of features.
api-version: 1.13
commands:
  epicvouchers:
    description: View information on this plugin.
    default: true
    aliases: [ev]
    usage: /ev