name: ${project.name}
description: ${project.description}
version: ${project.version}
api-version: 1.13

main: com.songoda.epicvouchers.EpicVouchers

author: Songoda
website: ${project.url}

commands:
  epicvouchers:
    description: View information on this plugin.
    default: true
    aliases: [ev]
    usage: /ev
