name: ${project.name}
description: ${project.description}
version: ${project.version}
api-version: 1.13

main: com.songoda.epicvouchers.EpicVouchers

author: Craftaro
website: ${project.url}

commands:
  EpicVouchers:
    default: true
    aliases: [ ev ]
