name: DeluxeVouchers
main: nl.marido.deluxevouchers.DeluxeVouchers
version: 6.0.6
author: Marido
website: https://marido.host/deluxevouchers
description: Enhance your server with awesome customizable vouchers with a lot of features.
commands:
 deluxevouchers:
  description: Administrator commands for the DeluxeVouchers resource.
  aliases: [dv, deluxev, dvouchers, deluxevoucher]